- name: Clone repo
  git: 'repo=git://github.com/sstephenson/rbenv.git dest={{ rbenv_root }} accept_hostkey=yes'

- name: Check ruby-build installed
  command: 'test -x {{ rbenv_root }}/plugins/ruby-build'
  register: 'plugin_installed'
  ignore_errors: yes

- name: 'Add bin to path'
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> {{ home }}/.bashrc
  when: 'plugin_installed|failed'

- name: Init
  shell: echo 'eval "$(rbenv init -)"' >> {{ home }}/.bashrc
  when: 'plugin_installed|failed'

- name: Clone ruby-build repo
  git: 'repo=git://github.com/sstephenson/ruby-build.git dest={{ rbenv_root }}/plugins/ruby-build accept_hostkey=yes'
  when: 'plugin_installed|failed'

- name: Check ruby {{ ruby_version }} installed
  shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv versions | grep {{ ruby_version }}'
  register: 'ruby_installed'
  ignore_errors: yes

- name: Install ruby {{ ruby_version }}
  shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv install {{ ruby_version }}'
  when: 'ruby_installed|failed'

- name: Set global ruby {{ ruby_version }}
  shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv global {{ ruby_version }}'
  when: 'ruby_installed|failed'

- name: 'Rehash'
  shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv rehash'
  when: 'ruby_installed|failed'

- name: Install bundler
  shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv exec gem install bundler'
  when: 'ruby_installed|failed'

- name: Change owner
  shell: 'chown -R {{ deploy_user }}:{{ deploy_user }} {{ rbenv_root }}'
  when: 'ruby_installed|failed'